// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE-0TdxHzQVlpHWD1BF1b9ZbNXJbD0Aic',
    appId: '1:333166939389:web:005c94d80ada237a0dc294',
    messagingSenderId: '333166939389',
    projectId: 'mald-application-app',
    authDomain: 'mald-application-app.firebaseapp.com',
    storageBucket: 'mald-application-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqyFSZEamqVFrfqTIZ5_oyW3V4kQMxF5Q',
    appId: '1:333166939389:android:963a3756767ad5680dc294',
    messagingSenderId: '333166939389',
    projectId: 'mald-application-app',
    storageBucket: 'mald-application-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4WLvDThj8brp7QXzpctgZhtym6PzqKYU',
    appId: '1:333166939389:ios:e9cc617163bcdfc80dc294',
    messagingSenderId: '333166939389',
    projectId: 'mald-application-app',
    storageBucket: 'mald-application-app.appspot.com',
    iosClientId: '333166939389-1n8cdoifb6dc2v06c762r2aocrv15op2.apps.googleusercontent.com',
    iosBundleId: 'com.example.maldRegistrationApp02',
  );
}
